# Generated by Django 4.2.8 on 2024-01-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
