# Generated by Django 4.2.8 on 2024-02-02 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0002_user_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('book_quantity', models.PositiveIntegerField()),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.schoolclass')),
            ],
        ),
    ]
