# Generated by Django 4.2.8 on 2024-02-02 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0003_library'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='school_class',
            new_name='student_class',
        ),
    ]
