# Generated by Django 4.2.8 on 2024-02-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentBook',
        ),
    ]
