# Generated by Django 4.2.8 on 2024-02-02 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0004_rename_school_class_library_student_class'),
        ('students', '0006_issuedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.library'),
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
